In [1]:
# Data cleaning in Python

In [2]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

Correctly identifying what type your data is is one of the easiest ways to avoid hampering your analysis due to data type constraints in the long run.

In [3]:
divorce_df = pd.read_csv('Data/divorce.csv')
divorce_df.head()

,divorce_date,dob_man,education_man,income_man,dob_woman,education_woman,income_woman,marriage_date,marriage_duration,num_kids
0,2020-12-09,1996-04-27,Master,116958.46,1973-07-16,High School,84203.16,2018-08-23,2.0,0.0
1,2013-08-14,1986-01-24,PhD,97513.28,1981-03-02,High School,28414.00,2018-10-11,11.1,0.0
2,2017-07-16,1979-03-11,High School,113949.89,1986-05-20,Master,36162.87,2006-07-25,11.3,0.0
3,2010-08-08,1988-01-06,Master,109482.74,1989-05-03,Bachelor,109855.42,2016-05-20,13.1,3.0
4,2021-03-09,1971-04-04,Master,79790.00,1993-05-11,Bachelor,80642.91,2017-07-21,14.8,0.0

In [4]:
# Print the information of ride_sharing
print(divorce_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   divorce_date       100 non-null    object
 1   dob_man            100 non-null    object
 2   education_man      100 non-null    object
 3   income_man         100 non-null    float64
 4   dob_woman          100 non-null    object
 5   education_woman    100 non-null    object
 6   income_woman       100 non-null    float64
 7   marriage_date      100 non-null    object
 8   marriage_duration  100 non-null    float64
 9   num_kids           100 non-null    float64
dtypes: float64(4), object(6)
memory usage: 7.9+ KB
None

In [5]:
print(divorce_df.isna().sum())

divorce_date         0
dob_man              0
education_man        0
income_man           0
dob_woman            0
education_woman      0
income_woman         0
marriage_date        0
marriage_duration    0
num_kids             0
dtype: int64

In [6]:
# Convert num_kids from float to integer
divorce_df['num_kids'] = divorce_df['num_kids'].astype('int')

# Write an assert statement confirming the change
assert divorce_df['num_kids'].dtype == 'int'

In [7]:
print(divorce_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   divorce_date       100 non-null    object
 1   dob_man            100 non-null    object
 2   education_man      100 non-null    object
 3   income_man         100 non-null    float64
 4   dob_woman          100 non-null    object
 5   education_woman    100 non-null    object
 6   income_woman       100 non-null    float64
 7   marriage_date      100 non-null    object
 8   marriage_duration  100 non-null    float64
 9   num_kids           100 non-null    int64
dtypes: float64(3), int64(1), object(6)
memory usage: 7.9+ KB
None

In [8]:
divorce_df.head()

,divorce_date,dob_man,education_man,income_man,dob_woman,education_woman,income_woman,marriage_date,marriage_duration,num_kids
0,2020-12-09,1996-04-27,Master,116958.46,1973-07-16,High School,84203.16,2018-08-23,2.0,0
1,2013-08-14,1986-01-24,PhD,97513.28,1981-03-02,High School,28414.00,2018-10-11,11.1,0
2,2017-07-16,1979-03-11,High School,113949.89,1986-05-20,Master,36162.87,2006-07-25,11.3,0
3,2010-08-08,1988-01-06,Master,109482.74,1989-05-03,Bachelor,109855.42,2016-05-20,13.1,3
4,2021-03-09,1971-04-04,Master,79790.00,1993-05-11,Bachelor,80642.91,2017-07-21,14.8,0

In [9]:
divorce_df['divorce_date'] = pd.to_datetime(divorce_df['divorce_date'])
divorce_df['dob_man'] = pd.to_datetime(divorce_df['dob_man'])
divorce_df['dob_woman'] = pd.to_datetime(divorce_df['dob_woman'])
print(divorce_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   divorce_date       100 non-null    datetime64[ns]
 1   dob_man            100 non-null    datetime64[ns]
 2   education_man      100 non-null    object
 3   income_man         100 non-null    float64
 4   dob_woman          100 non-null    datetime64[ns]
 5   education_woman    100 non-null    object
 6   income_woman       100 non-null    float64
 7   marriage_date      100 non-null    object
 8   marriage_duration  100 non-null    float64
 9   num_kids           100 non-null    int64
dtypes: datetime64[ns](3), float64(3), int64(1), object(3)
memory usage: 7.9+ KB
None

Another common data type problem is importing what should be numerical values as strings, as mathematical operations such as summing and multiplication lead to string concatenation, not numerical outputs.

In [10]:
fifa_df = pd.read_csv('Data/FIFA2021.csv', index_col = 0)
fifa_df.head()

,LongName,playerUrl,Nationality,Positions,Name,Age,↓OVA,POT,Team & Contract,ID,...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
photoUrl,,,,,,,,,,,,,,,,,,,,,
https://cdn.sofifa.com/players/158/023/21_60.png,Lionel Messi,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,RW ST CF,L. Messi,33,93,93,\n\n\n\nFC Barcelona\n2004 ~ 2021\n\n,158023,...,Medium,Low,5 ★,85,92,91,95,38,65,\n372
https://cdn.sofifa.com/players/020/801/21_60.png,C. Ronaldo dos Santos Aveiro,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,ST LW,Cristiano Ronaldo,35,92,92,\n\n\n\nJuventus\n2018 ~ 2022\n\n,20801,...,High,Low,5 ★,89,93,81,89,35,77,\n344
https://cdn.sofifa.com/players/200/389/21_60.png,Jan Oblak,http://sofifa.com/player/200389/jan-oblak/210005/,Slovenia,GK,J. Oblak,27,91,93,\n\n\n\nAtlético Madrid\n2014 ~ 2023\n\n,200389,...,Medium,Medium,3 ★,87,92,78,90,52,90,\n86
https://cdn.sofifa.com/players/192/985/21_60.png,Kevin De Bruyne,http://sofifa.com/player/192985/kevin-de-bruyn...,Belgium,CAM CM,K. De Bruyne,29,91,91,\n\n\n\nManchester City\n2015 ~ 2023\n\n,192985,...,High,High,4 ★,76,86,93,88,64,78,\n163
https://cdn.sofifa.com/players/190/871/21_60.png,Neymar da Silva Santos Jr.,http://sofifa.com/player/190871/neymar-da-silv...,Brazil,LW CAM,Neymar Jr,28,91,91,\n\n\n\nParis Saint-Germain\n2017 ~ 2022\n\n,190871,...,High,Medium,5 ★,91,85,86,94,36,59,\n273

In [11]:
# Strip Hits of \n
fifa_df['Hits'] = fifa_df['Hits'].str.strip('\n')
fifa_df.head()

,LongName,playerUrl,Nationality,Positions,Name,Age,↓OVA,POT,Team & Contract,ID,...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
photoUrl,,,,,,,,,,,,,,,,,,,,,
https://cdn.sofifa.com/players/158/023/21_60.png,Lionel Messi,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,RW ST CF,L. Messi,33,93,93,\n\n\n\nFC Barcelona\n2004 ~ 2021\n\n,158023,...,Medium,Low,5 ★,85,92,91,95,38,65,372
https://cdn.sofifa.com/players/020/801/21_60.png,C. Ronaldo dos Santos Aveiro,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,ST LW,Cristiano Ronaldo,35,92,92,\n\n\n\nJuventus\n2018 ~ 2022\n\n,20801,...,High,Low,5 ★,89,93,81,89,35,77,344
https://cdn.sofifa.com/players/200/389/21_60.png,Jan Oblak,http://sofifa.com/player/200389/jan-oblak/210005/,Slovenia,GK,J. Oblak,27,91,93,\n\n\n\nAtlético Madrid\n2014 ~ 2023\n\n,200389,...,Medium,Medium,3 ★,87,92,78,90,52,90,86
https://cdn.sofifa.com/players/192/985/21_60.png,Kevin De Bruyne,http://sofifa.com/player/192985/kevin-de-bruyn...,Belgium,CAM CM,K. De Bruyne,29,91,91,\n\n\n\nManchester City\n2015 ~ 2023\n\n,192985,...,High,High,4 ★,76,86,93,88,64,78,163
https://cdn.sofifa.com/players/190/871/21_60.png,Neymar da Silva Santos Jr.,http://sofifa.com/player/190871/neymar-da-silv...,Brazil,LW CAM,Neymar Jr,28,91,91,\n\n\n\nParis Saint-Germain\n2017 ~ 2022\n\n,190871,...,High,Medium,5 ★,91,85,86,94,36,59,273

In [12]:
fifa_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 18979 entries, https://cdn.sofifa.com/players/158/023/21_60.png to https://cdn.sofifa.com/players/255/958/21_60.png
Data columns (total 76 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   LongName          18979 non-null  object
 1   playerUrl         18979 non-null  object
 2   Nationality       18979 non-null  object
 3   Positions         18979 non-null  object
 4   Name              18979 non-null  object
 5   Age               18979 non-null  int64
 6   ↓OVA              18979 non-null  int64
 7   POT               18979 non-null  int64
 8   Team & Contract   18979 non-null  object
 9   ID                18979 non-null  int64
 10  Height            18979 non-null  object
 11  Weight            18979 non-null  object
 12  foot              18979 non-null  object
 13  BOV               18979 non-null  int64
 14  BP                18979 non-null  object
 15  Growth            18979 non-null  int64
 16  Joined            18979 non-null  object
 17  Loan Date End     1013 non-null   object
 18  Value             18979 non-null  object
 19  Wage              18979 non-null  object
 20  Release Clause    18979 non-null  object
 21  Attacking         18979 non-null  int64
 22  Crossing          18979 non-null  int64
 23  Finishing         18979 non-null  int64
 24  Heading Accuracy  18979 non-null  int64
 25  Short Passing     18979 non-null  int64
 26  Volleys           18979 non-null  int64
 27  Skill             18979 non-null  int64
 28  Dribbling         18979 non-null  int64
 29  Curve             18979 non-null  int64
 30  FK Accuracy       18979 non-null  int64
 31  Long Passing      18979 non-null  int64
 32  Ball Control      18979 non-null  int64
 33  Movement          18979 non-null  int64
 34  Acceleration      18979 non-null  int64
 35  Sprint Speed      18979 non-null  int64
 36  Agility           18979 non-null  int64
 37  Reactions         18979 non-null  int64
 38  Balance           18979 non-null  int64
 39  Power             18979 non-null  int64
 40  Shot Power        18979 non-null  int64
 41  Jumping           18979 non-null  int64
 42  Stamina           18979 non-null  int64
 43  Strength          18979 non-null  int64
 44  Long Shots        18979 non-null  int64
 45  Mentality         18979 non-null  int64
 46  Aggression        18979 non-null  int64
 47  Interceptions     18979 non-null  int64
 48  Positioning       18979 non-null  int64
 49  Vision            18979 non-null  int64
 50  Penalties         18979 non-null  int64
 51  Composure         18979 non-null  int64
 52  Defending         18979 non-null  int64
 53  Marking           18979 non-null  int64
 54  Standing Tackle   18979 non-null  int64
 55  Sliding Tackle    18979 non-null  int64
 56  Goalkeeping       18979 non-null  int64
 57  GK Diving         18979 non-null  int64
 58  GK Handling       18979 non-null  int64
 59  GK Kicking        18979 non-null  int64
 60  GK Positioning    18979 non-null  int64
 61  GK Reflexes       18979 non-null  int64
 62  Total Stats       18979 non-null  int64
 63  Base Stats        18979 non-null  int64
 64  W/F               18979 non-null  object
 65  SM                18979 non-null  object
 66  A/W               18979 non-null  object
 67  D/W               18979 non-null  object
 68  IR                18979 non-null  object
 69  PAC               18979 non-null  int64
 70  SHO               18979 non-null  int64
 71  PAS               18979 non-null  int64
 72  DRI               18979 non-null  int64
 73  DEF               18979 non-null  int64
 74  PHY               18979 non-null  int64
 75  Hits              16384 non-null  object
dtypes: int64(55), object(21)
memory usage: 11.1+ MB

In [14]:
print(fifa_df.isna().sum())

LongName          0
playerUrl         0
Nationality       0
Positions         0
Name              0
               ...
PAS               0
DRI               0
DEF               0
PHY               0
Hits           2595
Length: 76, dtype: int64

In [19]:
print(fifa_df['Hits'].unique())

['372' '344' '86' '163' '273' '182' '646' '79' '164' '170' '93' '131' '89'
 '90' '169' '187' '103' '317' '239' '56' '130' '229' '124' '172' '114'
 '46' '663' '479' '203' '198' '122' '565' '152' '140' '276' '209' '25'
 '136' '109' '139' '42' '99' '137' '166' '80' '104' '150' '112' '285'
 '133' '96' '69' '143' '100' '38' '83' '67' '207' '416' '315' '206' '424'
 '191' '454' '271' '249' '121' '246' '171' '148' '329' '70' '97' '73'
 '210' '82' '146' '62' '165' '129' '162' '35' '65' '47' '77' '106' '84'
 '1.3K' '310' '181' '364' '200' '141' '134' '259' '309' '367' '224' '211'
 '60' '176' '108' '63' '111' '52' '59' '350' '54' '117' '27' '91' '365'
 '312' '286' '157' '291' '245' '258' '233' '767' '288' '57' '115' '123'
 '142' '149' '227' '75' '53' '113' '71' '92' '144' '132' '125' '45' '158'
 '55' '43' '107' '24' '212' '21' '87' '39' '98' '192' '391' '23' '26' '13'
 '185' '177' '272' '193' '225' '78' '88' '37' '168' '85' '34' '1.5K' '48'
 '32' '215' '41' '20' '61' '68' '58' '19' '186' '17' '241' '574' '338'
 '274' '2.9K' '492' '670' '324' '352' '31' '30' '300' '189' '595' '127'
 '173' '159' '49' '36' '102' '280' '12' '14' '50' '76' '95' '51' '40' '22'
 '11' '9' '16' '10' '5' '222' '303' '268' '434' '256' '247' '248' '354'
 '289' '269' '237' '183' '6' '217' '155' '523' '921' '264' '72' '29' '476'
 '28' '205' '81' '393' '147' '74' '66' '33' '44' '314' '428' '261' '199'
 '281' '316' '118' '411' '396' '4' '794' '243' '204' '219' '167' '18'
 '356' '120' '561' '8' '101' '984' '2K' '603' '526' '1K' '343' '190' '154'
 '673' '194' '556' '128' '161' '494' '196' '232' '332' '283' '138' '15'
 '64' '94' '3' '7' '308' '382' '345' '275' '313' '398' '153' '935' '201'
 '699' '758' '745' '184' '1' '501' '145' '119' '255' '1.2K' '2' '253'
 '1.7K' '156' '238' '221' '175' '151' '500' '731' '532' '466' '535' '297'
 '265' '599' '234' '180' '195' '116' '423' '266' '560' '188' '244' '216'
 '496' '257' '226' '105' '412' '220' '970' '135' '360' '178' '1.1K' '326'
 '251' '369' '4.5K' '681' '700' '477' '333' '1.9K' '174' '406' '358' '555'
 '335' '856' '1.8K' '230' '250' '792' '400' '126' '342' '270' '529' '445'
 '830' '380' '881' '240' '160' '378' '598' '433' '202' nan]

In [ ]:
# Replace string 'nan' with actual NaN
fifa_df['Hits'] = fifa_df['Hits'].replace('nan', np.nan)

In [ ]:
def convert_hits(val):
    val = str(val)
    if 'K' in val:
        return int(float(val.replace('K', '')) * 1000)
    elif 'M' in val:
        return int(float(val.replace('M', '')) * 1000000)
    else:
        return int(val)

fifa_df['Hits'] = fifa_df['Hits'].apply(convert_hits)

In [ ]:
# Now decide how to handle the missing values
fifa_df['Hits'] = fifa_df['Hits'].fillna(0)   

# Then convert
fifa_df['Hits'] = fifa_df['Hits'].astype('int')

# Write an assert statement making sure of conversion
assert fifa_df['Hits'].dtype == 'int'

In [ ]:
# Print formed columns and calculate average ride duration 

print(fifa_df['Hits'].mean())